chance: 0.01
cornerstone_material: GRAY_CONCRETE
worlds:
  - world
surface_materials:
  - GRASS_BLOCK
  - DIRT
  - STONE
  - DIORITE
  - ANDESITE
  - WATER
  - COAL_ORE
  - IRON_ORE
  - SAND
  - SANDSTONE
  - LAVA
  - RED_SAND
  - SNOW
  - SNOW_BLOCK
  - POWDER_SNOW
  - ICE
  - MYCELIUM
  - MUD
  - TERRACOTTA
  - RED_TERRACOTTA
  - WHITE_TERRACOTTA
  - BROWN_TERRACOTTA
  - ORANGE_TERRACOTTA
  - YELLOW_TERRACOTTA
  - LIGHT_GRAY_TERRACOTTA
  - PODZOL
  - GRAVEL
structure_materials:
  - ACACIA_PLANKS
  - BIRCH_PLANKS
  - CRIMSON_PLANKS
  - DARK_OAK_PLANKS
  - JUNGLE_PLANKS
  - MANGROVE_PLANKS
  - OAK_PLANKS
  - SPRUCE_PLANKS
  - WARPED_PLANKS
  - CAULDRON
  - CRAFTING_TABLE
  - OAK_FENCE
  - CHEST
  - RAIL
  - STONE_BRICKS
  - MOSSY_STONE_BRICKS
  - COBBLESTONE
  - MOSSY_COBBLESTONE
  - DIRT_PATH
  - TORCH
  - WHITE_WOOL
  - YELLOW_WOOL
  - STRIPPED_OAK_WOOD
  - FARMLAND
  - HAY_BLOCK
  - OAK_STAIRS
  - REINFORCED_DEEPSLATE
  - DEEPSLATE_BRICKS
  - CRACKED_DEEPSLATE_BRICKS
  - POLISHED_DEEPSLATE
  - CHISELED_DEEPSLATE
  - GRAY_CARPET
  - CYAN_WOOL
  - BLUE_WOOL
  - LIGHT_BLUE_WOOL
  - BLUE_CARPET
  - POLISHED_BASALT
  - DEEPSLATE_TILE_STAIRS
  - CUT_SANDSTONE
  - TNT
  - CHISELED_SANDSTONE
  - SANDSTONE_STAIRS
  - OAK_TRAPDOOR
  - OAK_FENCE
  - GLASS
  - GLASS_PANE
  - BLACK_BED
  - BLUE_BED
  - BROWN_BED
  - CYAN_BED
  - GRAY_BED
  - GREEN_BED
  - LIGHT_BLUE_BED
  - LIGHT_GRAY_BED
  - LIME_BED
  - MAGENTA_BED
  - ORANGE_BED
  - PINK_BED
  - PURPLE_BED
  - RED_BED
  - WHITE_BED
  - YELLOW_BED
  - WHITE_CARPET
  - REDSTONE_TORCH
  - FURNACE
  - LADDER
  - PRISMARINE_BRICKS
  - PRISMARINE
  - SEA_LANTERN
  - SMOOTH_SANDSTONE
  - JUNGLE_BUTTON
  - SANDSTONE_WALL
  - SMOOTH_STONE_SLAB
